### ISSUE TITLE
sbt-idea broken?

### ISSUE THREAD

**Issue by fayimora** [etorreborre/s99#3]
I ran `sbt` and got this output.. Seems a dependency is broken. Any idea how I can fix this?

```
[info] Loading project definition from /Users/fayimora/Code/Scala/s99/project
[info] Updating {file:/Users/fayimora/Code/Scala/s99/project/}default-bc4aa0...
[info] Resolving com.github.mpeltonen#sbt-idea;1.0.0 ...
[warn]  module not found: com.github.mpeltonen#sbt-idea;1.0.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.github.mpeltonen/sbt-idea/scala_2.9.2/sbt_0.12/1.0.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/com.github.mpeltonen/sbt-idea/scala_2.9.2/sbt_0.12/1.0.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/fayimora/.ivy2/local/com.github.mpeltonen/sbt-idea/scala_2.9.2/sbt_0.12/1.0.0/ivys/ivy.xml
[warn] ==== sbt-idea-repo: tried
[warn]   http://mpeltonen.github.com/maven/com/github/mpeltonen/sbt-idea_2.9.2_0.12/1.0.0/sbt-idea-1.0.0.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/github/mpeltonen/sbt-idea_2.9.2_0.12/1.0.0/sbt-idea-1.0.0.pom
[info] Resolving org.scala-sbt#precompiled-2_10_0-m7;0.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.mpeltonen#sbt-idea;1.0.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      com.github.mpeltonen:sbt-idea:1.0.0 (sbtVersion=0.12, scalaVersion=2.9.2)
[warn] 
sbt.ResolveException: unresolved dependency: com.github.mpeltonen#sbt-idea;1.0.0: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:214)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:102)
    at sbt.IvySbt.liftedTree1$1(Ivy.scala:49)
    at sbt.IvySbt.action$1(Ivy.scala:49)
    at sbt.IvySbt$$anon$3.call(Ivy.scala:58)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:75)
    at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:79)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.liftedTree1$1(Locks.scala:51)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:51)
    at xsbt.boot.Locks$.apply0(Locks.scala:30)
    at xsbt.boot.Locks$.apply(Locks.scala:27)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:58)
    at sbt.IvySbt.withIvy(Ivy.scala:99)
    at sbt.IvySbt.withIvy(Ivy.scala:95)
    at sbt.IvySbt$Module.withModule(Ivy.scala:114)
    at sbt.IvyActions$.update(IvyActions.scala:121)
    at sbt.Classpaths$$anonfun$work$1$1.apply(Defaults.scala:951)
    at sbt.Classpaths$$anonfun$work$1$1.apply(Defaults.scala:949)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$54.apply(Defaults.scala:972)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$54.apply(Defaults.scala:970)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:974)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:969)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:977)
    at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:856)
    at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:853)
    at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
    at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
    at sbt.std.Transform$$anon$5.work(System.scala:71)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:238)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.github.mpeltonen#sbt-idea;1.0.0: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by SethTisue** [comment]
You can work around this by removing `project/plugins.sbt`

**Comment by SethTisue** [comment]
oh hmm but then I still get:

```
> test
[info] Updating {file:/Users/tisue/s99/}default-ee5b41...
[warn]  module not found: org.specs2#specs2_2.9.1;1.9-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/tisue/.ivy2/local/org.specs2/specs2_2.9.1/1.9-SNAPSHOT/ivys/ivy.xml
[warn] ==== snapshots-repo: tried
[warn]   http://oss.sonatype.org/content/repositories/snapshots/org/specs2/specs2_2.9.1/1.9-SNAPSHOT/specs2_2.9.1-1.9-SNAPSHOT.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/specs2/specs2_2.9.1/1.9-SNAPSHOT/specs2_2.9.1-1.9-SNAPSHOT.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.specs2#specs2_2.9.1;1.9-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: org.specs2#specs2_2.9.1;1.9-SNAPSHOT: not found
[error] Total time: 7 s, completed Jan 5, 2013 3:25:11 PM
```

which can be worked around by editing `build.sbt` and changing the specs version from `1.9-SNAPSHOT` to just `1.9`

**Comment by SethTisue** [comment]
I see https://github.com/etorreborre/s99/pull/4 has the specs version fix, but doesn't do anything about the sbt-idea issue

**Comment by fayimora** [comment]
Thanks that worked. I commented out the content of `plugins.sbt` since I am using vim.

I still get this after running `test`

```
> test
[info] Compiling 7 Scala sources to /Users/fayimora/Code/Scala/s99/target/scala-2.9.1/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.9.1.final. Compiling...
java.lang.OutOfMemoryError: PermGen space
Error during sbt execution: java.lang.OutOfMemoryError: PermGen space
```

**Comment by SethTisue** [comment]
the PermGen thing is a general sbt issue rather than something specific to s99. you may find it goes away if you just close sbt and try again. otherwise google "sbt PermGen"

**Comment by fayimora** [comment]
Yeah I noticed.. sbt just crashes after one run of `test`. Quite annoying

**Comment by TimMoore** [comment]
You can also fix this by changing the version number of `sbt-idea` to `"1.4.0"`.
